Mutable layer
Troon-Technologies-LLC/NowWhere-Contract pull request #9
Opened 2022-05-16 15:31 UTC by fahimasim

Pull request for Mutable Layer

2022-05-17 09:29 UTC, ObjectPlayer requested changes
Good work @fahimasim , I have added some request changes kindly work on that

2022-05-17 09:29 UTC, ObjectPlayer commented on contracts/NFTContract.cdc
> +        init(brandId: UInt64, schemaId: UInt64, maxSupply: UInt64, immutableData: {String: AnyStruct}, mutableData: {String: AnyStruct}) {
make mutable-layer as optional

2022-05-17 09:29 UTC, ObjectPlayer commented on README.md
> +Adding extra layer in template data mutable data
Add more description here about the mutable layer

2022-05-17 09:29 UTC, ObjectPlayer commented on contracts/NFTContract.cdc
> +       // let schema = TroonAtomicStandard.allSchemas[schemaId]!
If you don't need schema, than you can remove that line

2022-05-17 09:29 UTC, ObjectPlayer commented on contracts/NFTContract.cdc
> +                mutableData != nil: "MutableData must not be nil"
mutableData can be nil

2022-05-17 09:29 UTC, ObjectPlayer commented on contracts/NFTContract.cdc
> +            NFTContract.validateData(format:schema.format, data: immutableData)
First we need to validate data, than assign it. 
So move that line at top after pre-condition, it will enhance the execution time

2022-05-17 09:29 UTC, ObjectPlayer commented on contracts/NFTContract.cdc
> +           // NFTContract.validateData(format:schema.formatMutable, data: mutableData)
If we don't use that, than remove that line

2022-05-17 09:29 UTC, ObjectPlayer commented on contracts/NFTContract.cdc
> +        pub fun updateMutableData(key:String,value:AnyStruct) {
In this method, you can pass full mutable layer, instead of just key and value. So it will be `{String: AnyStruct}` , than we will add new attributes and update existing values of dictionary.

2022-05-17 09:29 UTC, ObjectPlayer commented on contracts/NFTContract.cdc
> +        pub fun updateTemplateMutableData(templateId: UInt64, key: String, value:AnyStruct)
same here, mutableData will be optional

2022-05-17 09:29 UTC, ObjectPlayer commented on contracts/NFTContract.cdc
>              pre {
Same here

2022-05-17 09:29 UTC, ObjectPlayer commented on contracts/NFTContract.cdc
>              NFTContract.allTemplates[NFTContract.lastIssuedTemplateId] = newTemplate
same here

2022-05-17 09:29 UTC, ObjectPlayer commented on contracts/NFTContract.cdc
> +        pub fun updateTemplateMutableData(templateId: UInt64, key: String, value:AnyStruct) {
parameter should be {String: AnyStruct}

2022-05-19 09:05 UTC, shamtroon commented
@fahimasim kindly remove conflicts first

2022-05-19 11:08 UTC, fahimasim commented
Conflicts has been removed

On Thu, May 19, 2022 at 2:05 PM shamtroon ***@***.***> wrote:

> @fahimasim <https://github.com/fahimasim> kindly remove conflicts first
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/Troon-Technologies-LLC/NowWhere-Contract/pull/9#issuecomment-1131438216>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AYJJFEE375QGVF4JR2KU73DVKX76TANCNFSM5WB4OHVA>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2022-05-19 13:24 UTC, noumankhan645 approved these changes

2022-05-25 14:50 UTC, ObjectPlayer commented
@fahimasim kindly resolve the conflicts

2022-05-26 12:46 UTC, merged